# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - nova5_group_controller
    - gripper_position_controller

  nova5_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

  gripper_position_controller:
    type: GripperCommand
    action_ns: gripper_cmd
    default: true
    joints:
      - robotiq_85_left_knuckle_joint